### ISSUE TITLE
Implementing onChange for Option components, debounce save actions

### ISSUE THREAD

**Issue by ethanlee16** [calblueprint/RMI#167]
### `<FreeOption />` changes
- [x] Implement `onChange` handler for `<FreeOption />` to inform Redux of changes in store _immediately_ for each key event
- [x] Debounce `updateAnswer` actions for a period of 3 seconds after `onChange` is called

### `<RangeOption />` changes
- [x] Allow for `onChange` handler to affect Redux store/React-controlled input without validating or selecting a range option: validate before saving, and save on entering within a range option

**Comment by kevintli** [comment]
For RangeOption, if the user types an answer outside of the range, we'd probably still want to send a fetch request to save it after a certain point. We could either do this onBlur (since range answers are much shorter so it might be okay to not save until they leave the field), or with a debounced updateAnswer action like FreeOptions
